[package]
name = "korabo-user-worker"
version = "0.1.0"
edition = "2021"

[dependencies]
aws_lambda_events = { version = "1.0.0", default-features = false, features = ["sqs"] }

lambda_runtime = "1.0.1"
tokio = { version = "1", features = ["macros"] }
aws-config = "1.8.14"
aws-sdk-dynamodb = "1.107.0"
user-core = { path = "../user-core" }
serde_json = "1.0.149"
