[package]
name = "korabo-user-handler"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.8.8"
lambda_http = "1.0.0"
serde_json = "1.0.149"

tokio = { version = "1", features = ["macros"] }
jwt = { git = "https://github.com/AhmadAiman2013/korabo-common.git", tag = "0.9.0" }
