[package]
name = "user-core"
version = "0.1.0"
edition = "2024"

[dependencies]
aws-sdk-dynamodb = "1.107.0"
chrono = { version = "0.4.44", features = ["serde"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_dynamo = { version = "4.3.0" , features = ["aws-sdk-dynamodb+1"]}
thiserror = "2.0.18"
